-- supabase/migrations/005_mdas_seed.sql
-- Run this in: Supabase Dashboard → SQL Editor (after 004_mdas.sql)
--
-- Seeds the official Government of Sierra Leone MDA list (179 entries,
-- with acronyms): offices, ministries, their departments/divisions/agencies,
-- and independent constitutional & oversight institutions.
--
-- Idempotent: re-running skips rows that already exist (unique on lower(name)).
-- created_by is left NULL for system-seeded rows.
--
-- NOTE: if you previously ran an older version of this seed WITHOUT acronyms,
-- clear the table first:  truncate table public.mdas cascade;

insert into public.mdas (name) values
-- ── Office of the President ────────────────────────────────────
('Office of the President (OoP)'),
('Chief Minister''s Office (CMO)'),
('Office of National Security (ONS)'),
('National Disaster Management Agency (NDMA)'),
('Presidential Delivery Unit (PDU)'),
('Public Sector Reform Unit (PSRU)'),
('Directorate of Science, Technology and Innovation (DSTI)'),
('State House Administration (SHA)'),
-- ── Ministry of Finance ────────────────────────────────────────
('Ministry of Finance (MoF)'),
('Accountant General''s Department (AGD)'),
('Budget Bureau (BB)'),
('Debt Management Division (DMD)'),
('Internal Audit Directorate (IAD)'),
('Public Investment Management Unit (PIMU)'),
('National Revenue Authority (NRA)'),
('National Public Procurement Authority (NPPA)'),
('Financial Intelligence Agency (FIA)'),
('National Commission for Privatization (NCP)'),
-- ── Ministry of Planning and Economic Development ──────────────
('Ministry of Planning and Economic Development (MoPED)'),
('National Planning Directorate (NPD)'),
('Monitoring & Evaluation Directorate (M&E)'),
('Development Cooperation Directorate (DCD)'),
('Public Investment Coordination (PIC)'),
-- ── Ministry of Justice ────────────────────────────────────────
('Ministry of Justice (MoJ)'),
('Law Officers'' Department (LOD)'),
('Legislative Drafting Division (LDD)'),
('Civil Division (CD)'),
('Criminal Division (CrD)'),
('Administrator & Registrar General (ARG)'),
('Legal Aid Board (LAB)'),
-- ── Ministry of Internal Affairs ───────────────────────────────
('Ministry of Internal Affairs (MoIA)'),
('Sierra Leone Police (SLP)'),
('Sierra Leone Immigration Department (SLID)'),
('Sierra Leone Correctional Service (SLCS)'),
('National Fire Force (NFF)'),
('National Civil Registration Authority (NCRA)'),
('National Drug Law Enforcement Agency (NDLEA)'),
-- ── Ministry of Defence ────────────────────────────────────────
('Ministry of Defence (MoD)'),
('Republic of Sierra Leone Armed Forces (RSLAF)'),
('Joint Force Command (JFC)'),
('Military Hospital (MH)'),
('Defence Headquarters (DHQ)'),
-- ── Ministry of Foreign Affairs and International Cooperation ──
('Ministry of Foreign Affairs and International Cooperation (MFAIC)'),
('Bilateral Affairs Directorate (BAD)'),
('Multilateral Affairs Directorate (MAD)'),
('Protocol Division (PD)'),
('Consular Affairs Division (CAD)'),
('Embassies & High Commissions (EHC)'),
-- ── Ministry of Health ─────────────────────────────────────────
('Ministry of Health (MoH)'),
('National Public Health Agency (NPHA)'),
('National Medical Supplies Agency (NMSA)'),
('Pharmacy Board of Sierra Leone (PBSL)'),
('District Health Management Teams (DHMTs)'),
('Teaching Hospitals (TH)'),
('Hospitals Directorate (HD)'),
('Disease Surveillance Division (DSD)'),
-- ── Ministry of Basic and Senior Secondary Education ───────────
('Ministry of Basic and Senior Secondary Education (MBSSE)'),
('Teaching Service Commission (TSC)'),
('West African Examinations Council – Sierra Leone (WAEC-SL)'),
('Inspectorate Directorate (ID)'),
('Curriculum Directorate (CD)'),
('Free Quality School Education Secretariat (FQSE)'),
-- ── Ministry of Technical and Higher Education ─────────────────
('Ministry of Technical and Higher Education (MTHE)'),
('Tertiary Education Commission (TEC)'),
('Universities (UNIs)'),
('Polytechnics (POLYs)'),
('Technical & Vocational Education and Training Institutions (TVET)'),
('Scholarships Directorate (SD)'),
-- ── Ministry of Agriculture and Food Security ──────────────────
('Ministry of Agriculture and Food Security (MAFS)'),
('Crops Division (CD)'),
('Livestock Division (LD)'),
('Agricultural Extension Services (AES)'),
('Seed Certification Unit (SCU)'),
('Agricultural Engineering Division (AED)'),
('Agricultural Research Institutes (ARI)'),
-- ── Ministry of Fisheries and Marine Resources ─────────────────
('Ministry of Fisheries and Marine Resources (MFMR)'),
('Fisheries Monitoring Centre (FMC)'),
('Licensing Unit (LU)'),
('Aquaculture Division (AD)'),
('Marine Surveillance Unit (MSU)'),
('Fisheries Research Division (FRD)'),
-- ── Ministry of Mines and Mineral Resources ────────────────────
('Ministry of Mines and Mineral Resources (MMMR)'),
('Geological Survey Department (GSD)'),
('Mines Inspectorate Division (MID)'),
('Licensing Directorate (LD)'),
('Precious Minerals Trading Unit (PMTU)'),
('National Minerals Agency (NMA)'),
-- ── Ministry of Trade and Industry ─────────────────────────────
('Ministry of Trade and Industry (MTI)'),
('Trade Directorate (TD)'),
('Industrial Development Directorate (IDD)'),
('Small and Medium Enterprise Directorate (SME)'),
('Consumer Protection Unit (CPU)'),
('Sierra Leone Standards Bureau (SLSB)'),
-- ── Ministry of Communications, Technology and Innovation ──────
('Ministry of Communications, Technology and Innovation (MoCTI)'),
('National Communications Authority (NatCA)'),
('National Cyber Security Coordination Centre (NCSCC)'),
('Government ICT Directorate (GICT)'),
('Postal Services Directorate (PSD)'),
('Digital Government Programmes (DGP)'),
-- ── Ministry of Information and Civic Education ────────────────
('Ministry of Information and Civic Education (MoICE)'),
('Government Information Service (GIS)'),
('Civic Education Directorate (CED)'),
('Public Relations Unit (PRU)'),
('Government Printing Department (GPD)'),
-- ── Ministry of Employment, Labour and Social Security ─────────
('Ministry of Employment, Labour and Social Security (MELSS)'),
('Labour Department (LD)'),
('Employment Services Directorate (ESD)'),
('Occupational Safety & Health Division (OSHD)'),
('Industrial Relations Division (IRD)'),
('National Social Security and Insurance Trust (NASSIT)'),
-- ── Ministry of Social Welfare ─────────────────────────────────
('Ministry of Social Welfare (MSW)'),
('Child Welfare Directorate (CWD)'),
('Disability Affairs Directorate (DAD)'),
('Family Support Services (FSS)'),
('Social Protection Programmes (SPP)'),
-- ── Ministry of Gender and Children''s Affairs ────────────────
('Ministry of Gender and Children''s Affairs (MoGCA)'),
('Gender Affairs Directorate (GAD)'),
('Child Protection Directorate (CPD)'),
('Women''s Empowerment Programmes (WEP)'),
('Gender Policy Unit (GPU)'),
-- ── Ministry of Youth Affairs ──────────────────────────────────
('Ministry of Youth Affairs (MoYA)'),
('Youth Development Directorate (YDD)'),
('Entrepreneurship Programmes (EP)'),
('Skills Development Division (SDD)'),
('National Youth Service (NYS)'),
-- ── Ministry of Sports ─────────────────────────────────────────
('Ministry of Sports (MoS)'),
('National Sports Authority (NSA)'),
('Stadium Management (SM)'),
('Sports Federations (SF)'),
('Community Sports Development (CSD)'),
-- ── Ministry of Tourism and Cultural Affairs ───────────────────
('Ministry of Tourism and Cultural Affairs (MTCA)'),
('National Tourist Board (NTB)'),
('Monuments and Relics Commission (MRC)'),
('National Museums (NM)'),
('Cultural Affairs Directorate (CAD)'),
-- ── Ministry of Transport and Aviation ─────────────────────────
('Ministry of Transport and Aviation (MTA)'),
('Sierra Leone Civil Aviation Authority (SLCAA)'),
('Sierra Leone Ports Authority (SLPA)'),
('Sierra Leone Maritime Administration (SLMA)'),
('Road Transport Directorate (RTD)'),
-- ── Ministry of Works and Public Assets ────────────────────────
('Ministry of Works and Public Assets (MWPA)'),
('Government Buildings Directorate (GBD)'),
('Public Assets Directorate (PAD)'),
('Engineering Services Division (ESD)'),
('Mechanical Services Division (MSD)'),
-- ── Ministry of Lands, Housing and Country Planning ────────────
('Ministry of Lands, Housing and Country Planning (MLHCP)'),
('Surveys Division (SD)'),
('Lands Division (LD)'),
('Physical Planning Division (PPD)'),
('Housing Directorate (HD)'),
('Land Registration Unit (LRU)'),
-- ── Ministry of Water Resources and Sanitation ─────────────────
('Ministry of Water Resources and Sanitation (MWRS)'),
('Guma Valley Water Company (GVWC)'),
('Sierra Leone Water Company (SALWACO)'),
('Rural Water Directorate (RWD)'),
('Sanitation Directorate (SanD)'),
-- ── Ministry of Local Government and Community Affairs ─────────
('Ministry of Local Government and Community Affairs (MLGCA)'),
('Freetown City Council (FCC)'),
('Bo City Council (BCC)'),
('Kenema City Council (KCC)'),
('Makeni City Council (MCC)'),
('District Councils (DCs)'),
('Chiefdom Administrations (CA)'),
-- ── Ministry of Public Administration and Political Affairs ────
('Ministry of Public Administration and Political Affairs (MoPAPA)'),
('Human Resource Management Office (HRMO)'),
('Public Service Commission (PSC)'),
('Public Service Training College (PSTC)'),
('Performance Management Directorate (PMD)'),
-- ── Independent Constitutional & Oversight Institutions ────────
('Parliament of Sierra Leone (PoSL)'),
('Judiciary of Sierra Leone (JSL)'),
('Audit Service Sierra Leone (ASSL)'),
('Anti-Corruption Commission (ACC)'),
('Electoral Commission for Sierra Leone (ECSL)'),
('Political Parties Regulation Commission (PPRC)'),
('Human Rights Commission of Sierra Leone (HRCSL)'),
('Right to Access Information Commission (RAIC)'),
('Statistics Sierra Leone (Stats SL)'),
('Sierra Leone Broadcasting Corporation (SLBC)'),
('National Commission for Social Action (NaCSA)')
on conflict (lower(name)) do nothing;
